import SideBar from '@/components/SideBar'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='h-full'>
          <div className='hidden md:flex h-full w-56 flex-col fixed inset-y-0 z-50'>
            <SideBar />
          </div>
          <main className='md:pl-56 h-full'>
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
